package com.xlc.community.community.model;

import org.springframework.stereotype.Repository;

import javax.persistence.Table;
import java.util.Date;
@Repository
@Table(name = "logInfo")
public class LogInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.logout_time
     *
     * @mbg.generated
     */
    private Date logoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.acc_type_id
     *
     * @mbg.generated
     */
    private String accTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.acc_type_name
     *
     * @mbg.generated
     */
    private String accTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.oper_name
     *
     * @mbg.generated
     */
    private String operName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.moudel
     *
     * @mbg.generated
     */
    private String moudel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.acc_id
     *
     * @mbg.generated
     */
    private String accId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.ent_name
     *
     * @mbg.generated
     */
    private String entName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.oper_state
     *
     * @mbg.generated
     */
    private String operState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginfo.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.id
     *
     * @return the value of loginfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.id
     *
     * @param id the value for loginfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.ip
     *
     * @return the value of loginfo.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.ip
     *
     * @param ip the value for loginfo.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.login_time
     *
     * @return the value of loginfo.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.login_time
     *
     * @param loginTime the value for loginfo.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.logout_time
     *
     * @return the value of loginfo.logout_time
     *
     * @mbg.generated
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.logout_time
     *
     * @param logoutTime the value for loginfo.logout_time
     *
     * @mbg.generated
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.login_name
     *
     * @return the value of loginfo.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.login_name
     *
     * @param loginName the value for loginfo.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.user_name
     *
     * @return the value of loginfo.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.user_name
     *
     * @param userName the value for loginfo.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.acc_type_id
     *
     * @return the value of loginfo.acc_type_id
     *
     * @mbg.generated
     */
    public String getAccTypeId() {
        return accTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.acc_type_id
     *
     * @param accTypeId the value for loginfo.acc_type_id
     *
     * @mbg.generated
     */
    public void setAccTypeId(String accTypeId) {
        this.accTypeId = accTypeId == null ? null : accTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.acc_type_name
     *
     * @return the value of loginfo.acc_type_name
     *
     * @mbg.generated
     */
    public String getAccTypeName() {
        return accTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.acc_type_name
     *
     * @param accTypeName the value for loginfo.acc_type_name
     *
     * @mbg.generated
     */
    public void setAccTypeName(String accTypeName) {
        this.accTypeName = accTypeName == null ? null : accTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.oper_name
     *
     * @return the value of loginfo.oper_name
     *
     * @mbg.generated
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.oper_name
     *
     * @param operName the value for loginfo.oper_name
     *
     * @mbg.generated
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.moudel
     *
     * @return the value of loginfo.moudel
     *
     * @mbg.generated
     */
    public String getMoudel() {
        return moudel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.moudel
     *
     * @param moudel the value for loginfo.moudel
     *
     * @mbg.generated
     */
    public void setMoudel(String moudel) {
        this.moudel = moudel == null ? null : moudel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.acc_id
     *
     * @return the value of loginfo.acc_id
     *
     * @mbg.generated
     */
    public String getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.acc_id
     *
     * @param accId the value for loginfo.acc_id
     *
     * @mbg.generated
     */
    public void setAccId(String accId) {
        this.accId = accId == null ? null : accId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.ent_name
     *
     * @return the value of loginfo.ent_name
     *
     * @mbg.generated
     */
    public String getEntName() {
        return entName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.ent_name
     *
     * @param entName the value for loginfo.ent_name
     *
     * @mbg.generated
     */
    public void setEntName(String entName) {
        this.entName = entName == null ? null : entName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.create_time
     *
     * @return the value of loginfo.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.create_time
     *
     * @param createTime the value for loginfo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.oper_state
     *
     * @return the value of loginfo.oper_state
     *
     * @mbg.generated
     */
    public String getOperState() {
        return operState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.oper_state
     *
     * @param operState the value for loginfo.oper_state
     *
     * @mbg.generated
     */
    public void setOperState(String operState) {
        this.operState = operState == null ? null : operState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.remark
     *
     * @return the value of loginfo.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.remark
     *
     * @param remark the value for loginfo.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginfo.account_name
     *
     * @return the value of loginfo.account_name
     *
     * @mbg.generated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginfo.account_name
     *
     * @param accountName the value for loginfo.account_name
     *
     * @mbg.generated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }
}