package com.xlc.community.community.mapper;

import com.xlc.community.community.model.LogInfo;
import com.xlc.community.community.model.LogInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
@Mapper
public interface LogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    long countByExample(LogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int deleteByExample(LogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int insert(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int insertSelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    List<LogInfo> selectByExampleWithRowbounds(LogInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    List<LogInfo> selectByExample(LogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    LogInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LogInfo record, @Param("example") LogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LogInfo record, @Param("example") LogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogInfo record);
}